services:
  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: IdentityService/IdentityService.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
    networks:
      - foundora-network
    depends_on:
      - identityservice.db 

  identityservice.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Q!w2e3r4
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
networks:
  foundora-network:
    driver: bridge